
import 'dart:io';
void main() {
  final rows = [
        '.BBBBBBBBBBBBBBBBBBBBBBWWWBBBBBBBBBBBBBBBBBBBBB.',
        'BBBBBBBBBBBBBBBBBBBWWWWWWWWWWWBBBBBBBBBBBBBBBBBB',
        'BBBBBBBBBBBBBBBBBBWWWWWWBWWWWWWBBBBBBBBBBBBBBBBB',
        'BBBBBBBBBBBBBBBBBWWWnnnnnnnnnWWWBBBBBBBBBBBBBBBB',
        'BBBBBBBBBBBBBBBBWWWnnnnnnnnnnnWWWBBBBBBBBBBBBBBB',
        'BBBBBBBBBBBBBBBWWWnnnnnnnnnnnnnWWWBBBBBBBBBBBBBB',
        'BBBBBBBBBBBBBBWWWnnnnWWWnnnnnnnnWWWBBBBBBBBBBBBB',
        'BBBBBBBBBBBBBBWWnnnnWWWWnnnnnnnnnWWBBBBBBBBBBBBB',
        'BBBBBBBBBBBBBBWWnnnWWWWWnnnnnnnnnWWBBBBBBBBBBBBB',
        'BBBBBBBBBBBBBBWWnnnWWWWWnnnnnnnnnWWBBBBBBBBBBBBB',
        'BBBBBBBBBBWWWWWWnnnWWWWWnnnnnnnnnWWWWWWBBBBBBBBB',
        'BBBBBBBBBWWWWWWnnnnnnnnnnnnnnnnnnnWWWWWWBBBBBBBB',
        'BBBBBBBBWWWQQQQQBBnnnnnnnnnnnnnYYBBHHHWWWBBBBBBB',
        'BBBBBBBWWWQQQQQQYYnnnnnnnnnnnnnYYHHHHHHWWWBBBBBB',
        'BBBBBBWWWQQQQQQQYYnnnnnnnnnnnnnYYHHHHHHHWWWBBBBB',
        'BBBBBWWWQQQQWWWQYYYnnnnnnnnnnnYYYHHHHHHHHWWWBBBB',
        'BBBBBWWQQQQWWWWQQYYYnnnnnnnnnYYYWHHHHHHHHHWWBBBB',
        'BBBBBWWQQQWWWWWQQQYYYnnnnnnnYYYWWHHHHHHHHHWWBBBB',
        'BBBBBWWQQQWWWWWQQQQYYYYYnYYYYYWWWHHHHHHHHHWWBBBB',
        'BBBBWWWQQQWWWWWQQQQQYYYYYYYYYWWWWHHHHHHHHHWWWBBB',
        'BBBBWWQQQQQQQQQQQQQQQQQQYHHHHHHHHHHHHHHHHHHWWBBB',
        'BBBBWWWMMQQQQQQQQQQQQQMMWDDHHHHHHHHHHHHHDDWWWBBB',
        'BBBBBWWMMQQQQQQQQQQQQQMMWDDHHHHHHHHHHHHHDDWWBBBB',
        'BBBBBWWMMQQQQQQQQQQQQQMMWDDHHHHHHHHHHHHHDDWWBBBB',
        'BBBBBWWMMMQQQQQQQQQQQMMMBDDDHHHHHHHHHHHDDDWWBBBB',
        'BBBBBWWWMMMQQQQQQQQQMMMJYJDDDHHHHHHHHHDDDWWWBBBB',
        'BBBBBBWWWMMMQQQQQQQMMMJYYYJDDDHHHHHHHDDDWWWBBBBB',
        'BBBBBBBWWWMMMMMQMMMMMJYJYJYJDDDDDHDDDDDWWWBBBBBB',
        'BBBBBBBBWWWMMMMMMMMMJYYYJYYYJDDDDDDDDDWWWBBBBBBB',
        'BBBBBBBBBWWWWWYMYJYJYJYJYJYJYJYJYDWWWWWWBBBBBBBB',
        'BBBBBBBBBBWWWWWYYYJYYYJYYYJYYYJYYWWWWWWBBBBBBBBB',
        'BBBBBBBBBBBBBWWJYJYJYJYJYJYJYJYJYWWBBBBBBBBBBBBB',
        'BBBBBBBBBBBBBWWWJYYYJYYYJYYYJYYYWWWBBBBBBBBBBBBB',
        'BBBBBBBBBBBBBBWWYJYJYJYJYJYJYJYJWWBBBBBBBBBBBBBB',
        'BBBBBBBBBBBBBBWWWYJYYYJYYYJYYYJWWWBBBBBBBBBBBBBB',
        'BBBBBBBBBBBBBBBWWJYJYJYJYJYJYJYWWBBBBBBBBBBBBBBB',
        'BBBBBBBBBBBBBBBWWWYYJYYYJYYYJYWWWBBBBBBBBBBBBBBB',
        'BBBBBBBBBBBBBBBBWWYJYJYJYJYJYJWWBBBBBBBBBBBBBBBB',
        'BBBBBBBBBBBBBBBBWWWYYYJYYYJYYWWWBBBBBBBBBBBBBBBB',
        'BBBBBBBBBBBBBBBBBWWJYJYJYJYJYWWBBBBBBBBBBBBBBBBB',
        'BBBBBBBBBBBBBBBBBWWWJYYYJYYYWWWBBBBBBBBBBBBBBBBB',
        'BBBBBBBBBBBBBBBBBBWWYJYJYJYJWWBBBBBBBBBBBBBBBBBB',
        'BBBBBBBBBBBBBBBBBBWWWYJYYYJWWWBBBBBBBBBBBBBBBBBB',
        'BBBBBBBBBBBBBBBBBBBWWJYJYJYWWBBBBBBBBBBBBBBBBBBB',
        'BBBBBBBBBBBBBBBBBBBWWWYYJYWWWBBBBBBBBBBBBBBBBBBB',
        'BBBBBBBBBBBBBBBBBBBBWWWJYJWWBBBBBBBBBBBBBBBBBBBB',
        'BBBBBBBBBBBBBBBBBBBBBWWWWWWWBBBBBBBBBBBBBBBBBBBB',
        '.BBBBBBBBBBBBBBBBBBBBBWWWWWBBBBBBBBBBBBBBBBBBBB.',
  ];
  final counts = <String, int>{};
  for(int r = 0; r < rows.length; r++) {
    for(int c = 0; c < rows[r].length; c++) {
      final char = rows[r][c];
      counts[char] = (counts[char] ?? 0) + 1;
    }
  }
  print(counts);
}

