import 'dart:io';

void main() {
  final List<String> originalTemplate = [
    "JJJJJJJJJJJJJJJJJJJJJJJJ.JJJJJJJJJJJJJJJJJJJJJJJ",
    "JJJJJJJJJJJJJJJJJJJJLLLLLLLLJJJJJJJJJJJJJJJJJJJJ",
    "JJJJJJJJJJJJJJJJJJJLLLLLLLLLLLJJJJJJJJJJJJJJJJJJ",
    "JJJJJJJJJJJJJJJJJJLLLLLLLLLLLLLJJJJJJJJJJJJJJJJJ",
    "JJJJJJJJJJJJJJJJJLLLLLLLLLLLLLLJJJJJJJJJJJJJJJJJ",
    "JJJJJJJJJJJJJJJJJLLKKKLLLLKKKLLLJJJJJJJJJJJJJJJJ",
    "JJJJJJJJJJJJJJJJLLKKKKKLLKKKKKLLJJJJJJJJJJJJJJJJ",
    "JJJJJJJJJJJJJJJJLLKKKKKLLKKKKKKLJJJJJJJJJJJJJJJJ",
    "JJJJJJJJJJJJJJJJLKKKLKKKLKKLSKKLLJJJJJJJJJJJJJJJ",
    "JJJJJJJJJJJJJJJJLKKKLKKKLKKLLKKLLJJJJJJJJJJJJJJJ",
    "JJJJJJJJJJJJJJJJLKKKKKKFFFKKKKKLLJJJJJJJJJJJJJJJ",
    "JJJJJJJJJJJJJJJLLKKKKFFFFFFKKKKLLJJJJJJJJJJJJJJJ",
    "JJJJJJJJJJJJJJJBLKKKKKFFFFKKKKKLBBJJJJJJJJJJJJJJ",
    "JJJJJJJJJJJJJJKBBBBKKKKKKKBBQBBBBBJJJJJJJJJJJJJJ",
    "JJJJJJJJJJJJJJJBBBBBBBBBBBQBBQBQBQJJJJJJJJJJJJJJ",
    "JJJJJJJJJJJJJJBQQBBBBBBBBBBBBQBBBBJJJJJJJJJJJJJJ",
    "JJJJJJJJJJJJJJBBBBBQQBBBBBBQBBBBQBBJJJJJJJJJJJJJ",
    "XJJJJJJJJJJJJJLBBBBBBBBBBBBQBBBBQBJJJJJJJJJJJJJX",
    "XXXXXXXXXXXXXXLLLBBBBBBBBBBQBBBBBLLXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXLLLLLSSSSMMMMSSBBBBBLLXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXLLLLLKKKKKKKKKSBBBBBLLLXXXXXXXXXXXX",
    "XXXXXXXXXXXXLLLLLKKKKKKKKKKSBBBBBLLLSXXXXXXXXXXX",
    "XXXXXXXXXXXLLLLLLKKKKKKKKKKSBBBBBLLLLXXXXXXXXXXX",
    "XXXXXXXXXXXLLLLLSKKKKKKKKKKSBBBBBLLLLLXXXXXXXXXX",
    "XXXXXXXXXXLLLLLLKKKKKKKKKKKSBBBBBLLLLLLXXXXXXXXX",
    "XXXXXXXXXLLLLLLLKKKKKKKKKKKBBBBBBLLLLLLXXXXXXXXX",
    "XXXXXXXXLLLLLLLLKKKKKKKKKKKBBBBBBLLLLLLLXXXXXXXX",
    "XXXXXXXLLLLLLLLLKKKKKKKKKKKBBBBBBLLLLLLLLXXXXXXX",
    "XXXXXMMLLLLLLLLLKKKKKKKKKKKBBBBBBLLLLLLLLLXXXXXX",
    "XXXXSSLLLLLLLLLLKKKKKKKKKKKBBBBBBBLLLLLLLLLXXXXX",
    "XXXXMLLLLLLXLLLLKKKKKKKKKKKBBBBBBBLLMLLLLLLLXXXX",
    "XXXMLLLLLLXXLLLLKKKKKKKKKKKSBBBBBBBLMXXLLLLLLXXX",
    "XXXLLLLMXXXXLLLLKKKKKKKKKKKSBBBBBBBLXXXXXLLLLLXX",
    "XXXXXXXXXXXXLLLLKKKKKKKKKKKSSSSSSLLLXXXXXXXXXXXX",
    "TTTTTTTTTTTTLLLLKKKKKKKKKKKKSKKKLLLLTTTTTTTTTTTT",
    "TTTTTTTTTTTTTLLLLKKKKKKKKKKKKKKKLLLLTTTTTTTTTTTT",
    "TTTTTTTTTTTTTLLLLKKKKKKKKKKKKKKMLLLTTTTTTTTTTTTT",
    "TTTTTTTTTTTTTLLLLMKKKKKKKKKKKKKLLLLTTTTTTTTTTTTT",
    "TTTTTTTTTTTTTTLLLLKKKKKKKKKKKKLLLLSTTTTTTTTTTTTT",
    "TTTTTTTTTTTTTTTLLLLKKKKKKKKKKLLLLLTTTTTTTTTTTTTT",
    "TTTTTTTTTTTTTTTLLLLLMKKKKKKKLLLLLTTTTTTTTTTTTTTT",
    "TTTTTTTTTTTTTTTTMLLLLLLSKLLLLLLLTTTTTTTTTTTTTTTT",
    "TTTTTTTTTTTTTTTTTFLLLLLLLLLLLLLTTTTTTTTTTTTTTTTT",
    "TTTTTTTTTTTTTTTTFFFFLLLLLLLLLFFFFTTTTTTTTTTTTTTT",
    "TTTTTTTTTTTTTTSFFFFFFFTTTTFFFFFFFFTTTTTTTTTTTTTT",
    "TTTTTTTTTTTTTTTSFFFFFFTTTTFFFFFFFSTTTTTTTTTTTTTT",
    ".TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT.",
    ".TTTTTTTTTTTTTTTTTTTTTTT.TTTTTTTTTTTTTTTTTTTTTT."
  ];

  final counts = <String, int>{};
  for (final row in originalTemplate) {
    for (int i = 0; i < row.length; i++) {
      counts[row[i]] = (counts[row[i]] ?? 0) + 1;
    }
  }
  print(counts);
}
